file=open('.\\07-FileHandling\\MeatAndFish.txt','r')
a = file.read()
file.close()
file1=open('.\\07-FileHandling\\GrainsAndBread.txt','r')
b = file1.read()
file1.close()
file2=open('.\\07-FileHandling\\shoppinglist.txt','w', encoding='UTF-8')
file2.write(f'{a}\n{b}')
file2.close()
