file = open('.\\07-FileHandling\\zad15.txt','r') 
a=int((len(file.readlines()))//5+1)
file.close()
file = open('.\\07-FileHandling\\zad15.txt','r') 
for i in range(a):
    print(file.readline(), end = '')
    print(file.readline(), end = '')
    print(file.readline(), end = '')
    print(file.readline(), end = '')
    print(file.readline(), end = '')
    a=input()
file.close()